### ISSUE TITLE
You should either initialize using getters and setters or parameterized constructors. Never assign directly to variablee

### ISSUE THREAD

**Issue by rampallydheeraj** [srikarrampa/JavaAssignments#10]
https://github.com/srikarrampa/JavaAssignments/blob/2330f9029b477c4d60b6ed6cb040ee0a32cd0142/FamilyTree/src/com/javaassignment/second/AdvancedFamilyTree.java#L141

**Comment by srikarrampa** [comment]
Can I assign null values initially and then assign my own values? 
Example: Person person = new Person(0,null,null,false);
Does this work?

**Comment by srikarrampa** [comment]
I have used getters and setters
