### ISSUE TITLE
Is id the unique identifier? What if it gets duplicated?

### ISSUE THREAD

**Issue by rampallydheeraj** [srikarrampa/JavaAssignments#11]
https://github.com/srikarrampa/JavaAssignments/blob/2330f9029b477c4d60b6ed6cb040ee0a32cd0142/FamilyTree/src/com/javaassignment/second/AdvancedFamilyTree.java#L143

**Comment by srikarrampa** [comment]
I have now checked if the user has entered an id which has already been chosen. Is there any other way if we can do this through static keyword?

**Comment by rampallydheeraj** [comment]
nope that shud be it
