### ISSUE TITLE
This part needs to be refactored to a different method under util package

### ISSUE THREAD

**Issue by rampallydheeraj** [srikarrampa/JavaAssignments#12]
https://github.com/srikarrampa/JavaAssignments/blob/2330f9029b477c4d60b6ed6cb040ee0a32cd0142/FamilyTree/src/com/javaassignment/second/AdvancedFamilyTree.java#L142

**Comment by srikarrampa** [comment]
Should I create another method for taking id?

**Comment by rampallydheeraj** [comment]
nope not required
